### ISSUE TITLE
Bot crashes on deleted issues

### ISSUE THREAD

**Issue by flatcap** [neomutt/neo-bot#5]
I thought it worked, but now it crashes on deleted issues,
e.g. `#2529`

https://github.com/neomutt/neo-bot/blob/7e6873db9ae0562a4549029865fed47868f3d660/neo-bot.py#L136

```
Traceback (most recent call last):
  File "./neo-bot.py", line 194, in <module>
    main()
  File "./neo-bot.py", line 190, in main
    bot.start()
  File "/home/neo-bot/.local/lib/python3.8/site-packages/irc/bot.py", line 354, in start
    super(SingleServerIRCBot, self).start()
  File "/home/neo-bot/.local/lib/python3.8/site-packages/irc/client.py", line 1202, in start
    self.reactor.process_forever()
  File "/home/neo-bot/.local/lib/python3.8/site-packages/irc/client.py", line 846, in process_forever
    consume(repeatfunc(one))
  File "/usr/lib/python3.8/site-packages/more_itertools/recipes.py", line 137, in consume
    deque(iterator, maxlen=0)
  File "/home/neo-bot/.local/lib/python3.8/site-packages/irc/client.py", line 827, in process_once
    self.process_data(in_)
  File "/home/neo-bot/.local/lib/python3.8/site-packages/irc/client.py", line 792, in process_data
    conn.process_data()
  File "/home/neo-bot/.local/lib/python3.8/site-packages/irc/client.py", line 268, in process_data
    self._process_line(line)
  File "/home/neo-bot/.local/lib/python3.8/site-packages/irc/client.py", line 299, in _process_line
    handler(arguments, command, source, tags)
  File "/home/neo-bot/.local/lib/python3.8/site-packages/irc/client.py", line 343, in _handle_message
    self._handle_event(event)
  File "/home/neo-bot/.local/lib/python3.8/site-packages/irc/client.py", line 376, in _handle_event
    self.reactor._handle_event(self, event)
  File "/home/neo-bot/.local/lib/python3.8/site-packages/irc/client.py", line 922, in _handle_event
    result = handler.callback(connection, event)
  File "/home/neo-bot/.local/lib/python3.8/site-packages/irc/client.py", line 1159, in _dispatcher
    method(connection, event)
  File "./neo-bot.py", line 69, in on_pubmsg
    return self._process_message(c, self.channel, e)
  File "./neo-bot.py", line 75, in _process_message
    issue = self.check_num(num, user, repo)
  File "./neo-bot.py", line 136, in check_num
    return Issue(deleted=True)
TypeError: __init__() missing 5 required positional arguments: 'date', 'type', 'user', 'title', and 'url'
```

**Comment by flatcap** [comment]
Fixed by 3a3963b
